
font=JetBrainsMonoNL Nerd Font Propo:weight=bold:size=20
prompt="~ "
# icon-theme=Papirus-Dark
# icon-enabled=yes
hide-before-typing=no
# fields=name,generic,comment,categories,filename,keywords
match-mode=fzf
match-counter=no
show-actions=no
lines=10
width=35
horizontal-pad=10
vertical-pad=10
inner-pad=10
layer=overlay
keyboard-focus=exclusive
exit-on-keyboard-focus-loss=yes

[key-bindings]
delete-line-forward=none
next=Down Control+j
prev=Up Control+k
cancel=Escape

[colors]
background=232136ff
text=908caaff
match=eb6f92ff
selection=c4a7e7ff
selection-text=e0def4ff
selection-match=eb6f92ff
border=ea9a97ff
prompt=c4a7e7ff

[border]
width=5
radius=10
