# NOTE: https://starship.rs/presets/

add_newline = true
follow_symlinks = false

palette = "rose-pine-moon"

[palettes.rose-pine-moon]
overlay = '#393552'
love = '#eb6f92'
gold = '#f6c177'
rose = '#ea9a97'
pine = '#3e8fb0'
foam = '#9ccfd8'
iris = '#c4a7e7'


[directory]
format = "[](fg:overlay)[ $path ]($style)[](fg:overlay) "
style = "bg:overlay fg:pine"

[git_branch]
format = "[](fg:overlay)[ $symbol $branch ]($style)[](fg:overlay) "
style = "bg:overlay fg:foam"
symbol = ""
truncation_length = 48
truncation_symbol = "*"

[git_status]
style = "bg:overlay fg:love"
format = '[](fg:overlay)([$all_status$ahead_behind]($style))[](fg:overlay) '
up_to_date = '[ ✓ ](bg:overlay fg:iris)'
# untracked = '[?\($count\)](bg:overlay fg:gold)'
# stashed = '[\$](bg:overlay fg:iris)'
# modified = '[!\($count\)](bg:overlay fg:gold)'
# renamed = '[»\($count\)](bg:overlay fg:iris)'
# deleted = '[✘\($count\)](style)'
# staged = '[++\($count\)](bg:overlay fg:gold)'
# ahead = '[⇡\(${count}\)](bg:overlay fg:foam)'
# diverged = '⇕[\[](bg:overlay fg:iris)[⇡\(${ahead_count}\)](bg:overlay fg:foam)[⇣\(${behind_count}\)](bg:overlay fg:rose)[\]](bg:overlay fg:iris)'
# behind = '[⇣\(${count}\)](bg:overlay fg:rose)'

[cmake]
disabled = true

[nodejs]
disabled = true

[python]
disabled = true

[lua]
disabled = true

[kubernetes]
disabled = true
#symbol = "⎈"
#format = 'on [$symbol](bright-black) [$context( \($namespace\))](dimmed green) '

